# Clean JDBC URL without query params in URL
spring.datasource.url=jdbc:postgresql://ep-blue-queen-atewevdy.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_YkD5JT0gM3td
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate Settings
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true